/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import java.awt.Color;

/**
 *
 * @author marcos
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        
        Color col = new Color(188, 227, 203);
        
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nomeUsusario = new javax.swing.JLabel();
        cargoUsuario = new javax.swing.JLabel();
        btnLogoff = new javax.swing.JButton();
        telaFundo = new javax.swing.JDesktopPane();
        lblFundo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        cadastro = new javax.swing.JMenu();
        menuHospede = new javax.swing.JMenu();
        cadastroHospede = new javax.swing.JMenuItem();
        consultaHospede = new javax.swing.JMenuItem();
        menuFuncionario = new javax.swing.JMenu();
        novoFuncionario = new javax.swing.JMenuItem();
        consultaFuncionario = new javax.swing.JMenuItem();
        reservas = new javax.swing.JMenu();
        menuAgenda = new javax.swing.JMenu();
        realizarReserva = new javax.swing.JMenuItem();
        consultaAgenda = new javax.swing.JMenuItem();
        quartos = new javax.swing.JMenu();
        novoQuartos = new javax.swing.JMenuItem();
        consultaQuarto = new javax.swing.JMenuItem();
        sair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela Principal");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/LogoPousada.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Usuário:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Cargo:");

        nomeUsusario.setText("Nome");

        cargoUsuario.setText("Nome cargo");

        btnLogoff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_logoff.png"))); // NOI18N
        btnLogoff.setText("Logoff");
        btnLogoff.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoffActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLogoff, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomeUsusario)
                            .addComponent(cargoUsuario))))
                .addGap(30, 30, 30))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addGap(30, 30, 30)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nomeUsusario))
                .addGap(3, 3, 3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cargoUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLogoff, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout telaFundoLayout = new javax.swing.GroupLayout(telaFundo);
        telaFundo.setLayout(telaFundoLayout);
        telaFundoLayout.setHorizontalGroup(
            telaFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaFundoLayout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addComponent(lblFundo)
                .addContainerGap(665, Short.MAX_VALUE))
        );
        telaFundoLayout.setVerticalGroup(
            telaFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaFundoLayout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addComponent(lblFundo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        telaFundo.setLayer(lblFundo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        cadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_cadastro.png"))); // NOI18N
        cadastro.setText("Cadastro   |");
        cadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        menuHospede.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_cliente.png"))); // NOI18N
        menuHospede.setText("Hóspede");
        menuHospede.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        cadastroHospede.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_novo_cadastro.png"))); // NOI18N
        cadastroHospede.setText("Cadastrar Hóspede");
        cadastroHospede.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cadastroHospede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroHospedeActionPerformed(evt);
            }
        });
        menuHospede.add(cadastroHospede);

        consultaHospede.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_consultar.png"))); // NOI18N
        consultaHospede.setText("Consultar");
        consultaHospede.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuHospede.add(consultaHospede);

        cadastro.add(menuHospede);

        menuFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_funcionario.png"))); // NOI18N
        menuFuncionario.setText("Funcionários");
        menuFuncionario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        novoFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_novo_cadastro.png"))); // NOI18N
        novoFuncionario.setText("Adicionar Funcionário");
        novoFuncionario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        novoFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoFuncionarioActionPerformed(evt);
            }
        });
        menuFuncionario.add(novoFuncionario);

        consultaFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_consultar.png"))); // NOI18N
        consultaFuncionario.setText("Consultar");
        consultaFuncionario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        consultaFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaFuncionarioActionPerformed(evt);
            }
        });
        menuFuncionario.add(consultaFuncionario);

        cadastro.add(menuFuncionario);

        jMenuBar1.add(cadastro);

        reservas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_reservas.png"))); // NOI18N
        reservas.setText("Reservas   |");
        reservas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        menuAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_agenda.png"))); // NOI18N
        menuAgenda.setText("Agenda");
        menuAgenda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        realizarReserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_nova_reserva.png"))); // NOI18N
        realizarReserva.setText("Nova Reserva");
        realizarReserva.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuAgenda.add(realizarReserva);

        consultaAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_consultar.png"))); // NOI18N
        consultaAgenda.setText("Consultar Agenda");
        consultaAgenda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        consultaAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaAgendaActionPerformed(evt);
            }
        });
        menuAgenda.add(consultaAgenda);

        reservas.add(menuAgenda);

        jMenuBar1.add(reservas);

        quartos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_quartos.png"))); // NOI18N
        quartos.setText("Quartos   |");
        quartos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        novoQuartos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_novo_quarto.png"))); // NOI18N
        novoQuartos.setText(" Adiconar Quarto");
        novoQuartos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        novoQuartos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoQuartosActionPerformed(evt);
            }
        });
        quartos.add(novoQuartos);

        consultaQuarto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_consultar.png"))); // NOI18N
        consultaQuarto.setText("Consultar Quartos");
        consultaQuarto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        quartos.add(consultaQuarto);

        jMenuBar1.add(quartos);

        sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_logout.png"))); // NOI18N
        sair.setText("Sair    ");
        sair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sairMouseClicked(evt);
            }
        });
        jMenuBar1.add(sair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(telaFundo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(telaFundo)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cadastroHospedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroHospedeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastroHospedeActionPerformed

    private void novoQuartosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoQuartosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_novoQuartosActionPerformed

    private void consultaAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaAgendaActionPerformed
        // TODO add your handling code here:
        TelaConsultaAgenda tela = new TelaConsultaAgenda();
        telaFundo.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_consultaAgendaActionPerformed

    private void btnLogoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoffActionPerformed

    private void sairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_sairMouseClicked

    private void consultaFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaFuncionarioActionPerformed
        // TODO add your handling code here:
        TelaConsultaFuncionario tela = new TelaConsultaFuncionario();
        telaFundo.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_consultaFuncionarioActionPerformed

    private void novoFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoFuncionarioActionPerformed
        // TODO add your handling code here:
        TelaCadastroFuncionario tela = new TelaCadastroFuncionario();
        telaFundo.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_novoFuncionarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogoff;
    private javax.swing.JMenu cadastro;
    private javax.swing.JMenuItem cadastroHospede;
    private javax.swing.JLabel cargoUsuario;
    private javax.swing.JMenuItem consultaAgenda;
    private javax.swing.JMenuItem consultaFuncionario;
    private javax.swing.JMenuItem consultaHospede;
    private javax.swing.JMenuItem consultaQuarto;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblFundo;
    private javax.swing.JMenu menuAgenda;
    private javax.swing.JMenu menuFuncionario;
    private javax.swing.JMenu menuHospede;
    private javax.swing.JLabel nomeUsusario;
    private javax.swing.JMenuItem novoFuncionario;
    private javax.swing.JMenuItem novoQuartos;
    private javax.swing.JMenu quartos;
    private javax.swing.JMenuItem realizarReserva;
    private javax.swing.JMenu reservas;
    private javax.swing.JMenu sair;
    private javax.swing.JDesktopPane telaFundo;
    // End of variables declaration//GEN-END:variables
}
